arch:
  - 'osl42-x86_64'

doc:
  - echo "No documentation to build"

doc_dir: ''

test:
  - eval `rmpm_do env --env-format embed_sh rafcon`
  - export PYTHONPATH=$PYTHONPATH:/volume/software/common/packages/rafcon/latest/tests
  - pytest /volume/software/common/packages/rafcon/latest/tests/network/test_single_client.py
  - pytest /volume/software/common/packages/rafcon/latest/tests/network/test_multi_clients.py
  
