arch:
  - 'osl42-x86_64'

doc:
  - echo "No documentation to build"

doc_dir: ''

test:
  - export PATH=$PATH:/volume/software/common/packages/rmpm/2.3.40/bin/osl42-x86_64
  - eval `rmpm_do env --env-format embed_sh rafcon`
  - export PYTHONPATH=$PYTHONPATH:/volume/software/common/packages/rafcon/latest/tests
  - pytest /volume/software/common/packages/rafcon/latest/tests/network/test_single_client.py
  - pytest /volume/software/common/packages/rafcon/latest/tests/network/test_multi_clients.py

env:

env_script:
  - 'free_display=$(python -c "import os;  print '':'' + str(max(map(lambda d: int(d[1]), os.listdir(''/tmp/.X11-unix''))+[-1])+1)")'
  - Xvfb `echo $free_display` -fp $HOME/.fonts -shmem -screen 0 1920x1200x24 & DISPLAY=$free_display
  - export DISPLAY
  - trap 'kill $(jobs -pr)' SIGINT SIGTERM EXIT
